BEGINBLOQUE=VDLISTADOPEDIDOSFILTRO.PAN
 PREREGISTRO=PRESEHIJO
  CAMPO=EXCLUIR,OCULTO,"________________"
ENDBLOQUE
BEGINBLOQUE=VDLISTADOPEDIDOS.PAN
  PADRE=    VDLISTADOPEDIDOSFILTRO.PAN
  POSX=1
  POSY=8
  PREREGISTRO=PRESEHIJO
  NOINSERT
  NOUPDATE
  NODELETE
  NOCOMMIT
  REGPAG=40
ENDBLOQUE