EXEC ALCCARGA.CARGATODO(0);
COMMIT;
EXEC ALCCARGA.CARGAARTICULOS(1);
COMMIT;
EXEC ALCCARGA.CARGALOTES(1);
COMMIT;
EXEC ALCCARGA.CARGAAGENCIAS(1);
COMMIT;       
EXEC ALCCARGA.CARGAINTERLOC(1);

EXEC ALCCARGA.CARGAPROVEEDOR;
COMMIT;     
EXEC ALCCARGA.CARGAPROYECTOS(1);
COMMIT;    
EXEC ALCCARGA.CARGAINICIAL(1);
COMMIT;
EXEC ALCCARGA.CARGAENTRADAS(1);
COMMIT;
EXEC ALCCARGA.CARGAPEDIDOS(1);
COMMIT;
EXEC ALCCARGA.CARGAACOND(1);
COMMIT; 
EXEC ALCCARGA.CARGASTOCK(1);
COMMIT;
SELECT 1,'Temp. 15ºC-25ºC',GRUPO_DE_ARTICULOS FROM ESAPART WHERE NUMERO_DE_ARTICULO='0000001';

SELECT * FROM VDLOTES WHERE CODLOT LIKE '%#%';

SELECT TO_DATE(2457227,'J') FROM DUAL;

SELECT * FROM VDSTOCK WHERE CODART='129';

       