SELECT * FROM 
(SELECT BUC.TIPOBULTO,BUL.CODART,SUM(BUL.CANTPEDIDA) PEDIDA,
           (CASE WHEN TIPOBULTO='E' THEN (SELECT NVL(SUM(CANTIDAD),0) FROM VDUBICA UBI,VDCONTE CNT,VDSTOCK STK WHERE UBI.CODUBI=CNT.CODUBI AND CNT.CODMAT=STK.CODMAT AND STK.CODART=BUL.CODART AND UBI.CODAREA='RP')
                      WHEN TIPOBULTO='U' THEN (SELECT NVL(SUM(CANTIDAD),0) FROM VDUBICA UBI,VDCONTE CNT,VDSTOCK STK WHERE UBI.CODUBI=CNT.CODUBI AND CNT.CODMAT=STK.CODMAT AND STK.CODART=BUL.CODART AND UBI.CODAREA='PU')
                                                                                                       END) STOCK
   FROM VDBULTOLIN BUL,VDBULTOCAB BUC,VDMOVIM MOV
 WHERE  MOV.CODMOV=BUL.CODMOV AND BUC.CODBULTO=BUL.CODBULTO AND MOV.STATUS BETWEEN 1900 AND 1950
 GROUP BY BUC.TIPOBULTO,BUL.CODART)
WHERE PEDIDA>STOCK;