SELECT COUNT(*) FROM TABLE(AS_READ_XLSX.LEEFICHERO('PFDATOS','FICHEROAS.XLSX'));

EXEC dbms_session.free_unused_user_memory;

SELECT * FROM TABLE(AS_READ_XLSX.READ(AS_READ_XLSX.FILE2BLOB('PFDATOS','FICHEROAS.XLSX'))) WHERE ROWNUM<400;

EXEC DBMS_SESSION.FREE_UNUSED_USER_MEMORY;

DECLARE
  RET BLOB;
BEGIN
  RET:=AS_READ_XLSX.FILE2BLOB('PFDATOS','FICHEROAS.XLSX');
END;    


SELECT * FROM V$TEMPORARY_LOBS ;

SELECT * FROM V$PROCESS;

SELECT * FROM v$sessmetric ;

BEGIN
   AS_XLSX.CLEAR_WORKBOOK;
   AS_XLSX.QUERY2SHEET('SELECT * FROM VDMOVIM WHERE ROWNUM<10000', TRUE, 'PFDATOS', 'FICHEROAS.XLSX');   
   AS_XLSX.CLEAR_WORKBOOK;
END;   