BEGIN
  FOR I IN (SELECT CODBULTO FROM VDBULTOCAB WHERE TIPOBULTO='E' AND STATUS=4100) LOOP
      KNAP.INICIABULTOCC(I.CODBULTO);
   END LOOP;
END;

SELECT CODUBI
                         FROM VDUBICA UB,TABLE(PFASIGNAUBI.DAMEPESOS(:MICODART)) ZON
                         WHERE VDCOMP.UBI2ART(UB.CODUBI, :MICODART)=0 AND VD.CONTIENE(:RANGOZONAS, UB.CODZONA,ADMITENULO=>0)>0 
                               AND NOT EXISTS (SELECT CNT.CODMAT FROM VDCONTE CNT,VDSTOCK STK WHERE CNT.CODUBI=UB.CODUBI AND CNT.CODMAT=STK.CODMAT)
                               AND NOT EXISTS (SELECT CODMOV FROM VDMOVIM WHERE CODUBIORI=UB.CODUBI AND STATUS<VDST.FMOVRECOGIDO)
                               AND NOT EXISTS (SELECT CODMOV FROM VDMOVIM WHERE CODUBIDEST=UB.CODUBI AND STATUS<VDST.FMOVACTUALIZA) AND
                               TIPOASIG='A'  AND CODAREA=:MICODAREA AND CODART IS NULL AND BLOQUEOSE='N' AND BLOQUEOSS='N' AND TIPOUBI='R' AND
                               UB.CODZONA=ZON.CODZONA+0
                         ORDER BY ZON.PESOZONA,UB.ORDENENTRADA;
                         
                         SELECT UB.CODUBI,CODZONA FROM VDUBICA UB,VDARTIC ART WHERE CODAREA='PU' AND ART.CODDIV='190' AND UB.CODART=ART.CODART GROUP BY UB.CODUBI,CODZONA;
                         
DELETE VDINFOHARDDISP;

DELETE VDINFODISP;

DECLARE
  CURSOR CSELUBI IS SELECT CODUBI,ROWNUM
                     FROM (SELECT CODUBI FROM VDUBICA WHERE CODZONA=12 AND CODAREA='PUL' ORDER BY ALTURA DESC,COLUMNA DESC); 
BEGIN
  FOR I IN CSELUBI LOOP
      INSERT INTO VDINFODISP (IDINFOPICK, NUMDISP, CODZONA,IDINFOPICKPADRE, DPADRE, IDINFOPICKLUZ, NUMLUZ, ORDENDISP, MAXCANTDISP, 
                              CANTALEATORIA, TIEMPOOK, TIEMPOFIN,NEXTTICK, INVCONT, CODUBI,CODBULTO, CONFIRMADO, CANTPEDIDADISP, 
                              CANTVALIDADADISP, STATUS, VDEXTRA,CODOPEMODIF, FECMODIF, HORAMODIF, 
                              CODCOMEN, CODMOV, QUEDAN)
                       VALUES (1,2000+I.ROWNUM,12,1,2000+I.ROWNUM,1,2000+I.ROWNUM,I.ROWNUM,999,
                               0,50,50,NULL,'S',I.CODUBI,'','N',0,
                               0,100,'',VDUSER.GETUSER,VD.FECHASYS,VD.HORASYS,
                               0,0,0);
      INSERT INTO VDINFOHARDDISP (IDINFOPICK, NUMDISP, IDINFOGEST,TEXTO, LUCES, TECLAS, STATUS, VDEXTRA, CODOPEMODIF, 
                                  FECMODIF, HORAMODIF, IDINFOPICKM, NUMDISPM, CODCOMEN, ESTADOBOT)
                           VALUES (1,2000+I.ROWNUM,1,'','','',200,'',VDUSER.GETUSER,
                                   VD.FECHASYS,VD.HORASYS,0,0,0,0);
   END LOOP;
END;    

SELECT * FROM VDINFOHARDDISP;                                        