CREATE TABLESPACE RMAN DATAFILE 
  'E:\oracle\oradata\SMMX\RMAN.DBF' SIZE 10432K AUTOEXTEND ON NEXT 64K MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE USER RMAN
  IDENTIFIED BY RMAN
  DEFAULT TABLESPACE RMAN
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for RMAN 
  GRANT RECOVERY_CATALOG_OWNER TO RMAN;
  GRANT RESOURCE TO RMAN;
  GRANT CONNECT TO RMAN;
  ALTER USER RMAN DEFAULT ROLE ALL;
  -- 1 System Privilege for RMAN 
  GRANT UNLIMITED TABLESPACE TO RMAN;
  -- 1 Tablespace Quota for RMAN 
  ALTER USER RMAN QUOTA UNLIMITED ON RMAN;

--conectado al rman catalog=rman/rman target=sys/sys
create catalog;
register database;
