DECLARE 
  MILOTE VDLOTES%ROWTYPE;
  MICODUBI VDUBICA.CODUBI%TYPE;
  MICODMOV NUMBER;
  RET NUMBEr;
  MSGERROR VARCHAR2(1000);
BEGIN
  SELECT * INTO MILOTE FROM VDLOTES WHERE ROWNUM=1;
  FOR I IN (SELECT * FROM VDARTIC WHERE CODART LIKE 'CPC%') LOOP
      MILOTE.CODART:=I.CODART;
      MILOTE.CODLOT:=I.CODART;
      MILOTE.CADUCI:='20201212';
      MILOTE.RETEST:='20200612';
      BEGIN
         INSERT INTO VDLOTES VALUES MILOTE;
         EXCEPTION WHEN OTHERS THEN NULL;
      END;
      SELECT CODUBI INTO MICODUBI FROM VDUBICA WHERE CODAREA='PU' AND CODUBI NOT IN (SELECT NVL(CODUBI,' ') FROM VDCONTE) AND ROWNUM=1;
      INSERT INTO VDCONTE (CODMAT, TIPOCONTE, CNTSSCC,CODUBI, POSCONTE, ALTURACONTE, STATUS, FECENTRADA, HORAENTRADA, FECCREADO, HORACREADO, VDEXTRA,CLAVEEXT, CODCOMEN, CODOPEMODIF,FECMODIF, HORAMODIF, PESOCONTE, 
                           LARGOCONTE, ANCHOCONTE, ULTSCAN, FECULTSCAN, HORAULTSCAN, CODBAREXT, CODMATEXT)
                VALUES (VDSECCNT.NEXTVAL,'CUBETA','',MICODUBI,1,0,0,VD.FECHASYS,VD.HORASYS,VD.FECHASYS,VD.HORASYS,'','',0,'X',VD.FECHASYS,VD.HORASYS,0,
                        0,0,0,0,'','','');
      MICODMOV:=0;
      VDMOV.CREAMOV(MICODMOV, 'REGULARIZA', 'REG+', 2300, 90006, MICODUBI, VDSECCNT.CURRVAL, I.CODART, I.CODART, I.UNIEMB, '0000000000', 200, 0, 0, '', 'CPC-4-006',MIBLOQUEOSDEST=>'0000000000');
      RET:=VDACTSTOCK.EJECUTAMOV(MICODMOV,MSGERROR);
      VDLOG.PONMENSAJE('ERROR',MSGERROR);
   END LOOP;
END LOOP; 

SELECT * FROM VDSTOCK WHERE CODART LIKE 'CPC%';  