
BEGIN
  FOR I IN (SELECT * FROM ALL_OBJECTS WHERE OBJECT_NAME='SYS_PLSQL_F04CF524_93_1') LOOP
      EXECUTE IMMEDIATE 'DROP TYPE '||I.OWNER||'.'||I.OBJECT_NAME;
   END LOOP;
END;   

DROP USER PFCOPIA CASCADE;