SELECT ANO,COUNT(DISTINCT(CODCLI)) CLIENTES,SUM(PESOPEDIDO)/1000 PESO,COUNT(DISTINCT CODPED),COUNT(DISTINCT CODBOLETA) BOLETAS
 FROM
 (SELECT ANO,CP.CODCLI,PESOPEDIDO,CP.CODPED,SE.CODBOLETA
  FROM SGLCABPE CP,SGLLINPE LP,SGLSERIE SE,
      (SELECT ROWNUM+2013 ANO,TO_CHAR(TO_DATE('01-01-'||(ROWNUM+2013),'DD-MM-YYYY'),'J') INIANO,TO_CHAR(TO_DATE('31-12-'||(ROWNUM+2013),'DD-MM-YYYY'),'J') FINANO 
         FROM SGLARTIC 
         WHERE ROWNUM<5)
  WHERE CP.FECTERMIN BETWEEN INIANO AND FINANO AND SE.CODSERIE=CP.CODSERIE AND
        CP.CODPED=LP.CODPED AND CP.ANOPED=LP.ANOPED AND CP.SEQPED=LP.SEQPED AND CP.CODDIV=LP.CODDIV AND LP.SERVIDA>0 AND NVL(CP.INTERNO,'N')='N' AND 
        CP.STATUS+0>750 AND CP.STATUS+0!=800
  GROUP BY ANO,CP.CODPED,CP.PESOPEDIDO,CP.CODCLI,SE.CODBOLETA)
 GROUP BY ANO;