EXEC ALCCREA.GENERANEVERA;

EXEC ALCCREA.GENERAEX;

EXEC ALCCREA.GENERATODO;

SELECT CODUBI,VDCLIPKG.PINTAUBICA(CODUBI) FROM VDUBICA WHERE CODUBI LIKE 'F%';

UPDATE VDUBICA SET VDEXTRA=SUBSTR(VDEXTRA,1,INSTR(VDEXTRA,'-',-1))||'0'||SUBSTR(VDEXTRA,INSTR(VDEXTRA,'-',-1)+1) WHERE INSTR(VDEXTRA,'-',-1)>LENGTH(VDEXTRA)-2 AND VDEXTRA IS NOT NULL;

SELECT UB.CODUBI,VDCLIPKG.PINTAUBICA(UB.CODUBI) NOMBRE,UB.CODAREA AREA,CLU.CODCLASE COMPATIBLE,CLU1.CODCLASE CONTENEDORES,UB.VDEXTRA
 FROM VDUBICA UB,VDCLASEUBI CLU,VDCLASEUBI CLU1
 WHERE UB.CODUBI=CLU.CODUBI AND CLU.CODCLASIF='COMPATIBLE' AND CLU1.CODUBI=UB.CODUBI AND CLU1.CODCLASIF='CONTENEDORES' AND
       UB.CODUBI LIKE 'F2%' AND UB.CODAREA IN ('CUBETAS','HR','NEVERA','ARCHIVO','BUNKER','MUESTROTEC','ULTRACONG','PREEXPED')
 ORDER BY CODUBI;
       
EXEC AS_XLSX.PRUEBA;    

select * from esapinic where codigo_articulo='0000525';  

SELECT * FROM EXCEPUBI; 

SELECT * FROM VDCONTE WHERE CODMAT IN (SELECT VDEXTRA FROM VDUBICA);

select * from telnetcliente;