SELECT UBI.CODAREA,STK.CODART,
      VD.TABLAARANGO('SELECT UBI1.CODUBI FROM VDUBICA UBI1,VDCONTE CNT,VDSTOCK STK1 WHERE STK1.CODMAT=CNT.CODMAT AND CNT.CODUBI=UBI1.CODUBI AND STK1.CODART='||STK.CODART||' AND UBI1.CODAREA='||UBI.CODAREA||')')
 FROM VDUBICA UBI,VDCONTE CNT,VDSTOCK STK
 WHERE STK.CODMAT=CNT.CODMAT AND CNT.CODUBI=UBI.CODUBI AND UBI.CODAREA IN ('RP','PU','PUL')
 GROUP BY UBI.CODAREA,STK.CODART
 HAVING COUNT(*)>1;
 
SELECT VD.TABLAARANGO('SELECT UBI1.CODUBI FROM VDUBICA UBI1,VDCONTE CNT,VDSTOCK STK1 WHERE STK1.CODMAT=CNT.CODMAT AND CNT.CODUBI=UBI1.CODUBI AND STK1.CODART='||:MICODART||' AND UBI1.CODAREA='||:MICODAREA||')') FROM DUAL; 