DECLARE
  MICODART VDARTIC.CODART%TYPE;
BEGIN
  FOR I IN (SELECT * FROM VDARTIC WHERE CODART LIKE 'CPC-4%') LOOP
      MICODART:=I.CODART;
      I.CODART:=REPLACE(I.CODART,'-','');
      INSERT INTO VDARTIC VALUES I;
      FOR J IN (SELECT * FROM VDLOTES WHERE CODART=MICODART) LOOP
          VDLOG.PONMENSAJE('PRUEBA','CAMBIANDO LOTE',J.CODART,'POR',I.CODART);
          J.CODART:=I.CODART;          
          INSERT INTO VDLOTES VALUES J;
       END LOOP;
      UPDATE VDCLASEARTIC SET CODART=I.CODART WHERE CODART=MICODART AND (CODCLASIF,CODCLASE) NOT IN (SELECT CODCLASIF,CODCLASE FROM VDCLASEARTIC WHERE CODART=I.CODART);
      UPDATE VDSTOCK SET CODART=I.CODART WHERE CODART=MICODART;
      UPDATE ALCENSAYOART SET CODART=I.CODART WHERE CODART=MICODART;
      UPDATE VDORDRECLIN SET CODART=I.CODART WHERE CODART=MICODART;
      UPDATE VDRECEPLIN SET CODART=I.CODART WHERE CODART=MICODART;
      UPDATE VDMOVIM SET CODART=I.CODART WHERE CODART=MICODART;
      DELETE VDLOTES WHERE CODART=MICODART;
      DELETE VDCLASEARTIC WHERE CODART=MICODART;
      DELETE VDARTIC WHERE CODART=MICODART;
  END LOOP;
 -- EXCEPTION WHEN OTHERS THEN ROLLBACK;
END;

SELECT * FROM VDLOTES WHERE CODART LIKE 'CPC%';

SELECT REPLACE('CPC-4-006-1','-','') FROM DUAL;