DECLARE
  MIPED VDPEDIDORIGCAB%ROWTYPE;
  MILIN VDPEDIDORIGLIN%ROWTYPE;
BEGIN
  SELECT * INTO MIPED FROM VDPEDIDORIGCAB WHERE CODPED='6344901';
  SELECT * INTO MILIN FROM VDPEDIDORIGLIN WHERE CODPED=MIPED.CODPED AND ROWNUM=1;
  MIPED.MARCASTK:='CPC-4-006';
  MIPED.CODDIV:='999';
  MIPED.STATUS:=-100;
  MILIN.CODDIV:=MIPED.CODDIV;
  MILIN.MARCASTK:=MIPED.MARCASTK;
  FOR I IN 1..20 LOOP
      MIPED.CODPED:=I;
      INSERT INTO VDPEDIDORIGCAB VALUES MIPED;
      FOR J IN 1..9 LOOP
          MILIN.CODPED:=MIPED.CODPED;
          MILIN.CODART:='CPC4006'||LTRIM(J);
          MILIN.CANTPEDIDA:=1;
          MILIN.SEQLINEA:=J;
          MILIN.SEQLINORIG:=J;
          MILIN.STATUS:=100;
          INSERT INTO VDPEDIDORIGLIN VALUES MILIN;
       END LOOP;
   END LOOP;
END;   