Insert into VDPROCESOS
   (GRUPOPROC, PROCESO, PARAM, FUNCIONPROC, LIBPROCESO, 
    ORDENACION, PERIODO, EJECUCIONES, CODCOMEN, CODOPEMODIF, 
    FECMODIF, HORAMODIF, ACTIVO)
 Values
   ('PICKING', 'INFOHARD', '1#VDINFO4.DLL', 'infotratahard', 'VDINFOHARD.DLL', 
    2, 5, 0, 92620, 'X', 
    2457811, '11:36:22', 'S');
Insert into VDPROCESOS
   (GRUPOPROC, PROCESO, PARAM, FUNCIONPROC, LIBPROCESO, 
    ORDENACION, PERIODO, EJECUCIONES, CODCOMEN, CODOPEMODIF, 
    FECMODIF, HORAMODIF, ACTIVO)
 Values
   ('PICKING', 'INFOHARDCARRO', '2#VDINFO4.DLL', 'infotratahard', 'VDINFOHARD.DLL', 
    2, 4, 0, 97814383, 'X', 
    2457807, '11:51:29', 'S');
Insert into VDPROCESOS
   (GRUPOPROC, PROCESO, PARAM, FUNCIONPROC, LIBPROCESO, 
    ORDENACION, PERIODO, EJECUCIONES, CODCOMEN, CODOPEMODIF, 
    FECMODIF, HORAMODIF, ACTIVO)
 Values
   ('PICKING', 'PICKING', '1#20##BEGIN :RET :=VDECOUNI.DISCRIMINANTE(:IDINFOPICK,:NUMDISP,:TECLA); END;#BEGIN VDECOUNI.TRATASCANINFO(:IDINFOGEST);END;#BEGIN VDECOUNI.TRATATICK(:IDINFOGEST);END;', 'xpick', 'XVDPICK.DLL', 
    0, 10, 0, 97674927, 'X', 
    2457815, '20:18:55', 'S');
COMMIT;
