
  DELETE VDINFOHARDDISP;
  
  DELETE VDINFODISP;
  
  update vdinfoharddisp set teclas='';
  
  
EXEC     PFCREADISP.CREAZONADER(9);


  SELECT * FROM  VDINFODISP WHERE NUMDISP>100000;
  
  SELECT * FROM VDUBICA WHERE CODZONA=2 AND CODAREA='PU';

BEGIN
  DELETE VDINFOHARDDISP WHERE NUMDISP>100000;
  DELETE VDINFODISP WHERE NUMDISP>100000;
  FOR I IN 1..6 LOOP
     PFCREADISP.CREAZONADER(I);
     PFCREADISP.CREAZONAIZQ(I);
   END LOOP;
END;

 EXEC PFCREADISP.PROCESA;
 
 exec pfcreadisp.actualizazona(1);
 
 
 SELECT VDBASCULA.PIDEPESOBASC(3) FROM DUAL;