
                    BEGIN
                      PFRPPU.TERMINAPRPUALTURA(:CODMAT);
                      EXCEPTION WHEN OTHERS THEN NULL;
                    END;
                    
                    
SELECT * FROM VDMOVIM WHERE STATUS<4000;  

SELECT * FROM VDMOVIM WHERE CODMOV IN (SELECT CODMOVESP FROM VDMOVIM WHERE STATUS<4000);   

SELECT * FROM VDCONTE WHERE CODMAT='1000000';   

SELECT * FROM VDSTOCK WHERE CODMAT='1000000';    


SELECT AGRUPALIN FROM VDARTIC WHERE CODART LIKE '190%';        