CREATE OR REPLACE VIEW SUIVI_OPERATEUR AS
SELECT MOV.CODOPEEJEMOV,BUL.CODBULTO,BUC.CODPED,BUC.TIPOBULTO,MOV.CODUBIORI,BUL.CODART,BUL.CANTSERVIDA,UBI.CODZONA,
       TO_DATE(BUL.FECPREPARA,'J') FECHA,BUL.HORAPREPARA
 FROM VDBULTOCAB BUC,VDBULTOLIN BUL,VDMOVIM MOV,VDPEDIDOCAB PEC,VDUBICA UBI
 WHERE MOV.CODMOV=BUL.CODMOV AND BUL.CODBULTO=BUC.CODBULTO AND 
       PEC.CODPED=BUC.CODPED AND PEC.ANOPED=BUC.ANOPED AND PEC.CODDIV=BUC.CODDIV AND PEC.SEQPED=BUC.SEQPED AND
       PEC.FECTERMIN=VD.FECHASYS AND UBI.CODUBI=MOV.CODUBIORI;
       
CREATE OR REPLACE VIEW SUIVI_COMMANDE AS
SELECT BUC.CODBULTO,BUC.TRACKINGAGE TACK_COLIS,BUC.CODPED ,PEC.TRACKINGAGE TRACK_COMMANDE, TO_DATE(BUC.FECCREADO,'J') FECHA,BUC.HORACREADO,
       TO_DATE(BUC.FECIMPRIME,'J') FECHAIMPRIME,BUC.HORAIMPRIME,
       TO_DATE(BUC.FECFINALIZA,'J') FECHAFINALIZA,BUC.HORAFINALIZA,
       TO_DATE(DECODE(SEX.FECEXPIDE,0,'',SEX.FECEXPIDE),'J') FECHAEXPIDE,SEX.HORAEXPIDE
 FROM VDBULTOCAB BUC,VDPEDIDOCAB PEC,VDSERIEEXP SEX
 WHERE BUC.FECFINALIZA=VD.FECHASYS-1 AND 
       PEC.CODPED=BUC.CODPED AND PEC.ANOPED=BUC.ANOPED AND PEC.CODDIV=BUC.CODDIV AND PEC.SEQPED=BUC.SEQPED AND
        SEX.CODSERIEEXP=PEC.CODSERIEEXP 
       ;
       
 CREATE OR REPLACE VIEW  SUIVI_GARE AS      
 SELECT UB.CODZONA,DECODE(UB.CODART,'-------------','',UB.CODART) CODART,UB.CODUBI,STK.ORDENSTK,STK.CODLOT,
        DECODE(STK.UNIEMB,0,0,CEIL(STK.CANTIDAD/STK.UNIEMB)) CAJAS,STK.CANTIDAD,STK.UNIEMB,
        UB.STKMAX,UB.STKURG
  FROM VDUBICA UB,VDSTOCK STK,VDCONTE CNT
  WHERE UB.CODAREA='PUC' AND CNT.CODMAT=STK.CODMAT(+) AND CNT.CODUBI(+)=UB.CODUBI;
     
  select * FROM VDUSUARIO;
  
  SELECT * FROM VDUBICA WHERE CODAREA='PUC'; 
  
  SELECT * FROM VDARTIC;
 
CREATE VIEW SUIVI_OPERATION_REAPRO  AS
  SELECT MOV.CODOPEEJEMOV,MOV.CODART,MOV.CODLOT,MOV.CODMATORI,MOV.CODMATTEMP,MOV.CANTIDAD,UBI.CODUBI,
         TO_DATE(MOV.FECINS,'J') FECHANEC,MOV.HORAINS HORANEC,
         TO_DATE(DECODE(MOV.FECPLANMOV,0,'',MOV.FECPLANMOV),'J') FECHAPLAN,MOV.HORAPLANMOV,
         TO_DATE(MOV.FECINIMOV,'J') FECHAREC,MOV.HORAINIMOV,
         TO_DATE(MOV.FECFINMOV,'J') FECHADEP,MOV.HORAFINMOV
 FROM VDMOVIM MOV,VDUBICA UBI
 WHERE MOV.FECFINMOV=VD.FECHASYS AND UBI.CODUBI=MOV.CODUBIDEST AND UBI.CODAREA='PUC';
 
 ALTER TABLE VDUSUARIO ADD TEMPORAL VARCHAR2(1) DEFAULT 'S';
 
 CREATE OR REPLACE VIEW SUIVE_COMMANDE_REFERENCE AS 
 SELECT PEC.CODPED,PEL.CODART,PEL.CANTPEDIDA,TO_DATE(DECODE(FECTERMIN,0,'',FECTERMIN),'J') FECHA,TIPOPEDIDO
  FROM VDPEDIDOCAB PEC,VDPEDIDOLIN PEL
  WHERE PEC.CODPED=PEL.CODPED AND PEC.CODDIV=PEL.CODDIV AND PEC.ANOPED=PEL.ANOPED AND PEL.SEQPED=PEC.SEQPED;
        