DROP USER PF001 CASCADE;

EXEC VDVISTAS.GENERATODOALM('001');

EXEC VDVISTAS.CREAVISTA('VDCLASEUBI', '001',1);

EXEC VDVISTAS.CREAVISTA('VDALMA', '001',' WHERE CODALM=''001''');

EXEC VDVISTAS.CREAVISTA('VDAREA', '001',' WHERE CODALM=''001''');

EXEC VDVISTAS.CREAVISTA('VDUBICA', '001',' WHERE CODAREA IN (SELECT CODAREA FROM VDAREA) OR CODAREA=''V10''',1);

EXEC VDVISTAS.CREAVISTA('VDCONTE', '001',' WHERE CODUBI IN (SELECT CODUBI FROM VDUBICA)',1);

EXEC VDVISTAS.CREAVISTA('VDMOVIM', '001',' WHERE CODUBIORI IN (SELECT CODUBI FROM VDUBICA) AND CODUBIDEST IN (SELECT CODUBI FROM VDUBICA)',1);


EXEC VDVISTAS.CREAVISTA('VDSTOCK', '001',' WHERE CODMAT IN (SELECT CODMAT FROM VDCONTE)',1);

SELECT * FROM PF001.VDARTIC;

SELECT * FROM PF001.VDALMA;

SELECT * FROM PF001.VDAREA;

SELECT * FROM PF001.VDUBICA;

EXEC VDVISTAS.CREARESTOVISTAS('001');

SELECT * FROM ALL_VIEWS WHERE OWNER='PF001';

SELECT DISTINCT OBJECT_TYPE FROM USER_OBJECTS;

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT IN (SELECT VIEW_NAME FROM ALL_VIEWS WHERE OWNER='PF001'); 

SELECT * FROM VDAREA;

GRANT CONNECT TO PF001 IDENTIFIED BY PF001;

SELECT * FROM USER_SEQUENCES;