BEGINBLOQUE = VDALEXPADREHIJOTEST1P.PAN
    PREREGISTRO=PRESEHIJO
	POSX=5
	POSY=1
	REGPAG=1
ENDBLOQUE
BEGINBLOQUE= VDALEXPADREHIJOTEST1H.PAN
	PADRE=VDALEXPADREHIJOTEST1P.PAN
	POSX=1
	POSY=7
	REGPAG=10
ENDBLOQUE