

CAMPO=TERMINAL, AUXILIAR, OCULTO, "__________________"

BEGINBLOQUE=VDUSUARIOREP.PAN
  PREREGISTRO=PRESEHIJO
  REGPAG=15
CAMPO=TERMINAL, AUXILIAR, VIRTUAL,OCULTO
ENDBLOQUE  
BEGINBLOQUE=VDASIUSUGRUREP.PAN
  PADRE=VDUSUARIOREP.PAN
  POSY=21
  REGPAG=20
ENDBLOQUE  
BEGINBLOQUE=VDASIUSUPRIREP.PAN
  PADRE=VDUSUARIOREP.PAN
  POSY=21
  POSX=58
  REGPAG=20
ENDBLOQUE  