# MOdulo   : VDNUMSERIESFMD.FRM
# Función  : Consulta de numero de serie en V10
#
# Creación : 01-04-2023
# Autor    : AGONZALEZ
###########################################
# HistOrico de cambios:
BEGINBLOQUE = VDNUMSERIESFPMD.PAN
    PREREGISTRO=PRESEHIJO
	POSX=1
	POSY=1
	REGPAG=1
ENDBLOQUE
BEGINBLOQUE= VDNUMSERIESFMD.PAN
	PREQUERY=QUERYHIJO
	PREREGISTRO=PRESEHIJO
	PADRE=VDNUMSERIESFPMD.PAN
	POSX=1
	POSY=12
	REGPAG=25
ENDBLOQUE