cd ..
CALL PONPATH

%DISCO%

CD %DISCO%\V10\FUENTES\AUTO\GENC
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDPERFILTAREA.DEF -FVDALGORITMOS.DEF -FVDPREPOSTALGORITMOS.DEF -FVDTAREAS.DEF -FVDPROCESOS.DEF -FVDCONFI.DEF
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDUSUARIO.DEF -FVDRECURSO.DEF -FVDRECTAREA.DEF -FVDCONVERSIONES.DEF -FVDARTIC.DEF -FVDCOMEN.DEF -FVDTIPOCOMEN.DEF
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDUBICA.DEF -FVDMOVIM.DEF -FVDSTATUS.DEF -FVDCONTE.DEF -FVDALMA.DEF -FVDFLUJOPARAM 
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDDEMANDACAB.DEF -FVDDEMANDALIN.DEF -FVDAREA.DEF -FVDDEMANDATIPO.DEF -FVDCLASEARTIC.DEF
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvdpedidos.h  -FVDAGENCIA.DEF -FVDBULTOLIN.DEF -FVDBULTOCAB.DEF -FVDPEDIDOLIN.DEF -FVDPEDIDOCAB.DEF 
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvdpedidos.h  -FVDASIGNAGE.DEF -FVDCAJAS.DEF -FVDCOLCAMBIOVOL.DEF 
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDSTOCKFUENTE.DEF -FVDIMPRETIPO.DEF -FVDIMPREGRUPO.DEF -FVDIMPRESORAS.DEF -FVDIMPRESPOOL.DEF -FVDIMPREASIG.DEF 
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDINTERFASETAB.DEF -FVDINTERFASECAB.DEF -FVDINTERFASELIN.DEF -FVDINTERFCARGACAB.DEF -FVDINTERFCARGALIN.DEF
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDDIVIS.DEF -FVDLOTES.DEF -FVDLOTEBLOQ.DEF -FVDRECEPLIN.DEF -FVDCONCEPTOFORM.DEF
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvdpedidos.h  -FVDSERIEPREP.DEF -FVDSERIEEXP.DEF -FVDPEDIDORIGCAB.DEF -FVDPEDIDORIGLIN.DEF  -FVDDEFCAMPO.DEF -FVDDEFBLOQUE.DEF 
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDPAIS.DEF -FVDCORRSMTP.DEF -FVDLOTESHIST.DEF -FVDSTOCK.DEF -FVDTIPORDRECLIN.DEF -FVDORDRECCAB.DEF -FVDORDRECLIN.DEF -FVDTRADCODIGO.DEF -FVDINTERFCARGACAB.DEF -FVDINTERFCARGALIN.DEF -FVDEMPRE.DEF -FVDGRUPOSERV.DEF -FVDSERVICIOS.DEF
START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvdlecturas.h -FVDSCANLECT.DEF -FVDSCANMIRROR.DEF -FVDSCANNUMSERIE.DEF -FVDINFOLECTURAS.DEF -FVDORDENADORES.DEF
START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDINFODISP.DEF -FVDINFODISPBULTO.DEF -FVDINFOPARAMCC.DEF -FVDINFOHARDDISP.DEF -FVDINFOOPECOLOR.DEF -FVDINFOMENUS.DEF -FVDINFOHARD.DEF -FVDOPEACTIVIDAD.DEF -FVDBULTOCABPINV.DEF -FVDBULTOZONA.DEF -FVDZONAS.DEF
#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvd.h -FVDGRAFICA.DEF -FVDGRAFICAEJE.DEF -FVDGRAFICASERIE.DEF -FVDGRAFICAPIE.DEF

#START /WAIT VDGENC -OU%BDATOS% -LNGENC -Hvdpedidos.h  -FVDPEDIDORIGCAB.DEF -FVDPEDIDORIGLIN.DEF 

#D %DISCO%\V10\FUENTES\AUTO\GENCLIBRE
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDPICKING
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDPICKUNI
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDPICKCC
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDPICKINV
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDSTOCKAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDRUTAS
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDBULTOAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDUBICAR 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDCOMENTARIOS 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDSEMAFOROAUX 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDDEMANDAAUX 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDRESERVAAUX 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDRECARGAAUX 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDPEDIDORIGAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDASIGNAGEAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDPEDIDOAUX 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDACTSTKBUL 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDCAJAVOLAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDZONASAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDINTERFASES
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDARTICULOS
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDIMPRESIONAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDCONTEAUX 
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDMOVAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvdpedidos.h -FVDSERIEAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDCORREOSAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDSTOCKFUENTEAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDINFOGESTICKS
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDBULTOSPINV
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDSERVICIOAUX
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDVERIF
#START /WAIT VDGENCLIBRE -OU%BDATOS% -LNGENC -Hvd.h -FVDORAERR



