CALL PONPATH
echo bajar
CALL %DISCO%\V10\CMD\BORRAFICH %DISCO%\V10DATOS\BAJAR\BAK *
echo subir
CALL %DISCO%\V10\CMD\BORRAFICH %DISCO%\V10DATOS\SUBIR\BAK *
echo log
CALL %DISCO%\V10\CMD\BORRAFICH %DISCO%\V10DATOS\LOG *
EXIT