# Módulo   : VDPICKUNIART.PAN
# Función  : Formulario de recogida de bultos de unidades.
#            Pantalla de lectura de articulo.
#
# Creación : 13-05-2008
# Autor    : JMM
###########################################
# Histórico de cambios:
# M001 - DFL - 05/03/2019: SI ES UN NÚMERO SERIALIZADO, NO FORZAMOS A LEER LA MATRICULA, SÓLO EVALUAMOS EL NUMERO DE SERIE LEIDO
# M002 - DFL - 06/03/2019: BUSCAR LA MÁSCARA DEL SERIALIZADO EN LA TABLA ALCMASCARANUMSERIE, PARA VER EN QUE POSICION DE TODO EL CODIGO, ESTÁ EL NUMERO DE SERIE QUE ESPERAMOS
# M003 - DFL - 12/03/2019: BUSCAR EL BULTO DESDE VDSTOCK, PORQUE NO SE HEREDA EN EL MOVIMIENTO
PICKING POR TERMINAL
_10_______ _10_______
BULTO @L@@ PED: _20___________
UBICACION : _12_________
MATRICULA : _20_________________
BULTO-MAT : _20_________________
            _20_________________  
ARTICULO: _20_____________
_________________________________________
_________________________________________
LOTE: _20_________________

[41;37mCANTIDAD : #L#############[40;37m

SERIE: _____________________________________
       _400____________________________________________________________________________________________________________________________________________________________________________________________
|

PREQUERY=FEJECUTA("CLIMPIA","ERROR\n LIMPIANDO CAMPOS",
                  "CSELLONGERROR","ERROR\n OBTENIENDO VARIABLE\n LONGITUDERROR",
                  FIF(FCONGELAMOV(":CODMOV"),FSUCCESS,FEJECUTA("CMOVPDTESTOCK","ERROR ACTUALIZANDO MOVTO A PDTESTOCK",
                                                                FCOMMIT,"",
                                                                FPOSICIONABLOQUE("VDPICKUNIERRCONGELA.PAN"))),"ERROR\n CONGELANDO MOVIMIENTO\n :CODMOV",
                  "CSELLOTEYCANTIDAD","ERROR\n OBTENIENDO LOTE Y CANTIDAD",
                  FCOMMIT,"ERROR\n HACIENDO COMMIT",   
                  "+CSELDECIMALES","",
#M003 INICIO
#                  "+CVERBULTO","ERROR BULTO",
#M003 FIN
#M001 INICIO
#                  FPOSICIONACAMPO(FSUCCESS,"CODMATLEIDA"),"")
                  FPOSICIONACAMPO(FSUCCESS,"LEIDO"),""                
#M001 FIN
                )

POSTQUERY=FEJECUTA(FIF("CSELNULL",FPOSICIONABLOQUE("VDPICKUNIANUL.PAN"),FSUCCESS),"ERROR\n CARGANDO BLOQUE\nVDPICKUNIANUL.PAN",
                   FIF(FEJECUTAMOVSYNC("ACTSTKORIGEN","ACTSTKDESTINO",":CODMOV",":CODRECURSO"),
                       FSUCCESS,
                       FEJECUTA("CDIVIDEERROR","ERROR\nDIVIDIENDO ERROR MOV",FFAILURE,":MSGERROR")),"",                                                
                   FCOMMIT,"ERROR\n HACIENDO COMMIT",
                   FIF("CSELLINEASPEND",FPOSICIONABLOQUE("VDPICKUNIDEC.PAN"),
                                        FPOSICIONABLOQUE("VDPICKUNIFIN.PAN")),"ERROR\n CARGANDO SIGUIENTE\n BLOQUE")

#DEFINICION DE CAMPOS
CAMPO=CODRECURSO,VIRTUAL,NOENTER
CAMPO=CODOPE,VIRTUAL,NOENTER
CAMPO=NBULTO,VIRTUAL,NOENTER
CAMPO=CODPED,VIRTUAL,NOENTER
CAMPO=CODUBI,VIRTUAL,NOENTER
CAMPO=CODMAT,VIRTUAL,NOENTER
CAMPO=BULTOMAT2,NOENTER
#M001 INICIO
#CAMPO=CODMATLEIDA,SCAN,POSTCHANGE=FEJECUTA("CVERIFMAT","MATRICULA INCORRECTA")
CAMPO=CODMATLEIDA,NOENTER
#M001 FIN
CAMPO=CODART,VIRTUAL,NOENTER
CAMPO=DESART1,VIRTUAL,NOENTER
CAMPO=DESART2,VIRTUAL,NOENTER
CAMPO=CODLOT,NOENTER
CAMPO=CANTIDAD,NOENTER,CONVIERTE=FCONVIERTEARTFROMDB(":CODART");FCONVIERTEART2DB(":CODART")
CAMPO=CODBULTO,VIRTUAL,NOENTER,OCULTO
CAMPO=ESPERADO,NOENTER
CAMPO=LEIDO,SCAN,AUTOENTER,POSTCHANGE=FEJECUTA("CDAMEMASCARA","ERROR AL VER LA MASCARA\nDEL NUMERO DE SERIE","CVERLEIDO","NUMERO DE SERIE INCORRECTO")
CAMPO=CODMOV,VIRTUAL,OCULTO
CAMPO=MSGERROR,OCULTO,"_512_"
CAMPO=LONGERROR,OCULTO,"@@@"
CAMPO=CODARTIN,OCULTO,"_20_"
CAMPO=CODLOTIN,OCULTO,"_20_"
CAMPO=INICIO,OCULTO,"@@@@"
CAMPO=LONGITUD,OCULTO,"@@@@"
CAMPO=LEIDOAUX,OCULTO,"_200_"

#DEFINICION DE CURSORES
CURSOR=CLIMPIA SELECT '' CODMATLEIDA,'' LEIDO FROM DUAL;

#M002 INICIO
#CURSOR=CVERLEIDO SELECT :LEIDO FROM DUAL WHERE :LEIDO=:ESPERADO;
CURSOR=CVERLEIDO SELECT SUBSTR(:LEIDO,:INICIO,:LONGITUD) LEIDOAUX FROM DUAL WHERE SUBSTR(:LEIDO,:INICIO,:LONGITUD)=:ESPERADO;
CURSOR=CSETLEIDO SELECT :LEIDOAUX LEIDO FROM DUAL;
#M002 FIN

CURSOR=CSELLONGERROR SELECT VD.GETPROP('LONGITUDERROR') LONGERROR FROM DUAL;

CURSOR=CVERIFMAT SELECT :CODMAT FROM DUAL WHERE :CODMAT=:CODMATLEIDA;

CURSOR=CSELDECIMALES SELECT ART.DECIMALES CANTIDAD__DECIMALES FROM VDARTIC ART WHERE CODART = :CODART;

CURSOR=CSELNULL SELECT :LEIDO FROM DUAL WHERE :LEIDO IS NULL;


CURSOR=CSELLOTEYCANTIDAD SELECT CODLOT,CANTIDAD,VD.PIECE(NUMEROSERIE,'#',2) ESPERADO,(SELECT BULTO FROM VDSTOCK WHERE NUMEROSERIE=A.NUMEROSERIE AND CODMAT= A.CODMATORI) BULTOMAT2 FROM VDMOVIM A WHERE CODMOV=:CODMOV;

CURSOR=CDIVIDEERROR BEGIN :MSGERROR:=VD.DIVERRORRADIO(:V10ERROR,:LONGERROR);
                    END;@
                    
CURSOR=CMOVPDTESTOCK UPDATE VDMOVIM 
                        SET CODRECURSO=NULL, STATUS=VDST.FMOVPDTESTOCK,
                            CODOPEMODIF = :CODOPE, FECMODIF = VD.FECHASYS, HORAMODIF = VD.HORASYS
                      WHERE CODMOV=:CODMOV;    
                      
CURSOR=CSELLINEASPEND SELECT :CODBULTO
                        FROM VDBULTOCAB CB, VDBULTOLIN LB
                       WHERE CB.CODBULTO = :CODBULTO AND
                             LB.CODBULTO = CB.CODBULTO AND
                             LB.STATUS = VDST.FBULASERVIR;
#M002 INICIO
CURSOR=CDAMEMASCARA BEGIN VDMANIP.DAMEMASCARA (:CODART, :CODLOT, :INICIO, :LONGITUD); END;@
#M002 FIN

#M003 INICIO
CURSOR=CVERBULTO SELECT BULTO BULTOMAT2 FROM VDSTOCK WHERE VD.PIECE(NUMEROSERIE,'#',2)=:ESPERADO AND CODMAT = :CODMAT;
#M003 FIN