BEGINBLOQUE=VDETIQUETADOCC.PAN
ENDBLOQUE
BEGINBLOQUE=VDEANETIQCC.PAN
  PADRE=VDETIQUETADOCC.PAN
  POSY=7
ENDBLOQUE
BEGINBLOQUE=VDBULETIQCC.PAN
  PADRE=VDEANETIQCC.PAN
  PREREGISTRO=PRESEHIJO
  POSY=12
  REGPAG=15
ENDBLOQUE 
#BEGINBLOQUE=VDBULETIQCCBUL.PAN
#  PADRE=VDBULETIQCC.PAN
#  POSY=31
#  REGPAG=10
#ENDBLOQUE 
