IF %1'A'=='A' GOTO FIN
PUSHD .
cd %1
rem echo off
REM ESTE COMANDO METE EN UN ARCHIVO COMPRIMIDO TODOS LOS .DAT
REM QUE HAY EN EL SUBDIRECTORIO SUPERIOR. %DATE% ES UNA VARIABLE
REM DE SISTEMA QUE GUARDA LA FECHA DEL DÍA. OJO PONER EN OPCIONES REGIONALES FORMATO FECHA DD-MM-YY
REM SOBRE TODO NUNCA CON / QUE SE INTERPRETA COMO DIRECTORIO

ZIP -D -j %1\ZIP\%DATE:~0,2%-%DATE:~3,2%-%DATE:~6,4%.ZIP %1\*.%2
IF ERRORLEVEL 1 GOTO POP
del /Q %1\*.%2
CD ZIP
REM ESTE COMANDO SACA LA LISTA DE FICHEROS QUE HAY EN EL DIRECTORIO,
REM SÓLO LOS NOMBRES DE FICHERO, Y ORDENADOS POR ANTIGÜEDAD DE MÁS NUEVO
REM A MÁS ANTIGUO, Y LO METE EN EL FICHERO 'LISTA.TXT'. COMO LISTA.TXT
REM EXISTE Y ES EL MÁS NUEVO, ESTARÁ EL PRIMERO DE LA LISTA. HAY QUE TENERLO
REM EN CUENTA PARA DECIDIR CUANTAS LINEAS HAY QUE SALTARSE EN EL COMANDO
REM SIGUIENTE.

DIR %1\*.* /B /O-D > %1\LISTA.TXT

REM ESTE COMANDO ABRE EL FICHERO 'LISTA.TXT', SE SALTA LAS TREINTA
REM PRIMERAS LINEAS [SKIP=30], TOMA LOS NOMBRES DE FICHERO QUE HAY A PARTIR
REM DE LA SÉPTIMA LINEA [TOKENS=1*] (QUE CASUALMENTE ES UNO Y COINCIDE CON
REM EL FICHERO MÁS ANTIGUO), LO METE EN %%I Y LO BORRA.

FOR /F "skip=120 tokens=1*" %%I IN (%1\LISTA.TXT) DO DEL %1\%%I
DEL /Q %1\LISTA.TXT
:POP
POPD
:FIN