#IF EXIST PONPATH%COMPUTERNAME%.CMD PONPATH%COMPUTERNAME%.CMD
IF %PLATFORM%A== A SET PLATFORM=win32
SET V10EDITOR=C:\Program Files (x86)\Notepad++\notepad++.exe

SET DISCO=D:\V10
SET BDATOS=RDRP/Z4pATa2020#-@RDRP
SET DIRLOG=%DISCO%\V10DATOS\LOG
SET CLIENTE=%DISCO%\REDUR
SET NLS_LANG=SPANISH_SPAIN
SET DIRV10INCLUDE=%CLIENTE%\FUENTES\AUTO\GENC;%CLIENTE%\FUENTES;%DISCO%\V10\FUENTES;%DISCO%\V10\FUENTES\FORMS;%DISCO%\V10\FUENTES\EXECPROC;%DISCO%\V10\FUENTES\PICKING;%DISCO%\V10\FUENTES\IMPRESION;%DISCO%\V10\FUENTES\ST;%DISCO%\V10\FUENTES\LECTURAS;%DISCO%\V10LIB\FUENTES;%DISCO%\V10LIB\FUENTES\FORMS;%DISCO%\V10LIB\FUENTES\ORACLE;%DISCO%\V10LIB\FUENTES\OCIINCLUDE;%DISCO%\V10LIB\FUENTES\SSL;%DISCO%\V10LIB\FUENTES\SSL\OPENSSL;%DISCO%\V10LIB\FUENTES\WWW
SET DIRV10LIB=%CLIENTE%\BIN%PLATFORM%;%DISCO%\V10\BIN%PLATFORM%;%DISCO%\V10LIB\BIN%PLATFORM%

SET PATHV10=%CLIENTE%\PATH;%DISCO%\V10\PATH;%CLIENTE%\FUENTES;%DISCO%\V10\FUENTES\ST;%DISCO%\V10LIB\WWW;%DISCO%\V10\BIN%PLATFORM%
SET PATH=%DISCO%\V10LIB\BIN%PLATFORM%;%CLIENTE%\BIN%PLATFORM%;%DISCO%\V10\BIN%PLATFORM%;%PATH%