SET V10EDITOR=NOTEPAD++
SET DISCO=D:\V10
SET CLIENTE=REDUR
SET BDATOS=RDRD/Z4pATa2020#-@RDRD

SET DIRLOG=%DISCO%\V10DATOS\LOG\

SET DIRV10INCLUDE=%DISCO%\V10\FUENTES;%DISCO%\V10\FUENTES\IMPRESION;%DISCO%\V10\FUENTES\ST;%DISCO%\V10LIB\FUENTES;%DISCO%\V10LIB\FUENTES\www;%DISCO%\V10LIB\FUENTES\ssl;%DISCO%\V10LIB\FUENTES\ssl\openssl;%DISCO%\V10\FUENTES\LECTURAS

SET DIRV10=%DISCO%\V10\FUENTES;%DISCO%\V10\FUENTES\ST;%DISCO%\V10\FUENTES\LECTURAS;%DISCO%\V10\FUENTES\ETIQUETAS;%DISCO%\V10\FUENTES\PICKING;%DISCO%\V10\FUENTES\IMPRESION;%DISCO%\V10\FUENTES\VERTIS;%DISCO%\V10\FUENTES\FORMS;
SET DIRV10LIB=%DISCO%\V10LIB\FUENTES;%DISCO%\V10LIB\FUENTES\WWW;%DISCO%\V10LIB\FUENTES\SSL;%DISCO%\V10LIB\FUENTES\SSL\OPENSSL;%DISCO%\V10LIB\FUENTES\FORMS;


%DISCO%
CD \V10\BIN
SET PATHV10=%DISCO%\%CLIENTE%\PATH\FRMRADIO;%DISCO%\%CLIENTE%\PATH;%DISCO%\V10\PATH;%DISCO%\V10\FUENTES\ST;%DISCO%\V10LIB;%DISCO%\V10\BIN
SET PATH=%DISCO%\V10LIB\BIN;%DISCO%\V10\BIN;%DISCO%\%CLIENTE%\BIN;%PATH%
