# Módulo   : VDRECEPCION.FRM
# Función  : RECEPCIÓN DE MERCANCÍA
#
###########################################
# Histórico de cambios:
# 
CAMPO=CODOPE,OCULTO,"_10_________"
CAMPO=CODRECURSO,OCULTO,"_10_________"

#PREFORM=FEJECUTA(FPOSICIONABLOQUE("VDRECPROTO.PAN"),"")
#0 
BEGINBLOQUE=VDRECPROTO.PAN  
ENDBLOQUE
#1 
BEGINBLOQUE=VDGESMUELLE.PAN
    PADRE=VDRECPROTO.PAN
ENDBLOQUE
