// Modulo generado automaticamente a partir de VDARTIC.DEF

VDEXPORT diccionario dart;
#define ARTNUMCOL	89
typedef struct {
        char    rowid[ROWIDLON];
        char    codart[LCODART];
        char    coddiv[LCODDIV];
        char    codartdiv[LCODARTDIV];
        char    codnac[LCODNAC];
        char    codean[LCODEAN];
        char    desart[LDESART];
        char    desartalt[LDESARTALT];
        double  uniemb;
        long    embcont;
        long    embpiso;
        char    tipoembadef[LTIPOEMBADEF];
        char    tipocontedef[LTIPOCONTEDEF];
        char    unidades[LUNIDADES];
        char    unidadeshost[LUNIDADESHOST];
        char    ordensal[LORDENSAL];
        char    trazabulto[LTRAZABULTO];
        long    decimales;
        char    tipovol[LTIPOVOL];
        double  largouni;
        double  anchouni;
        double  altouni;
        long    coefuni;
        double  pesouni;
        long    unipaq;
        long    largopaq;
        long    anchopaq;
        long    altopaq;
        long    coefpaq;
        double  pesopaq;
        char    invcont[LINVCONT];
        char    petinicaja[LPETINICAJA];
        char    confpicking[LCONFPICKING];
        long    fecvignp;
        double  pvpvigente;
        double  pvpnuevo;
        double  pvpantiguo;
        double  pvdvigente;
        double  pvdnuevo;
        double  pvdantiguo;
        double  pvpivavigente;
        double  pvpivanuevo;
        double  pvpivaantiguo;
        char    swttumbable[LSWTTUMBABLE];
        char    swtanulado[LSWTANULADO];
        char    swtetiq[LSWTETIQ];
        char    agrupalin[LAGRUPALIN];
        long    tpcverif;
        char    swtanalisis[LSWTANALISIS];
        char    swtgenerico[LSWTGENERICO];
        char    swtstock[LSWTSTOCK];
        char    swtlote[LSWTLOTE];
        long    tretest;
        char    uniretest[LUNIRETEST];
        long    tavisa;
        char    uniavisa[LUNIAVISA];
        char    formatolote[LFORMATOLOTE];
        char    muestroteca[LMUESTROTECA];
        long    nummuestras;
        long    tcaduc;
        char    unicaduc[LUNICADUC];
        long    pedmultiplo;
        char    tipoajuste[LTIPOAJUSTE];
        long    minpendiente;
        long    maxuni;
        long    minpal;
        char    tipocajc[LTIPOCAJC];
        long    pesocajc;
        long    largocajc;
        long    anchocajc;
        long    altocajc;
        char    swtpesacaja[LSWTPESACAJA];
        double  tpcmargenpeso;
        long    margenpesosup;
        long    margenpesoinf;
        char    pickinv[LPICKINV];
        char    swtnumeroserie[LSWTNUMEROSERIE];
        char    swtactivo[LSWTACTIVO];
        char    tipoverifciega[LTIPOVERIFCIEGA];
        long    codcomen;
        char    codopemodif[LCODOPEMODIF];
        long    fecmodif;
        char    horamodif[LHORAMODIF];
        long    cajacubeta;
        long    maxlongns;
        long    minlongns;
        char    swthost[LSWTHOST];
        long    cubetacaja;
        char    tipoabc[LTIPOABC];
    } vdartics;

// Prototipos de funciones definidas en VDARTIC.C
VDEXPORT diccionario *ARTdamediccionario(void);
VDEXPORT int ARTselcodart(char *codart,vdartics *art);
VDEXPORT int ARTbuscacodean(char *codean,vdartics *art);
VDEXPORT int ARTnextcodean(vdartics *art);
VDEXPORT int ARTselvdartic(char *codart,vdartics *art);
VDEXPORT int ARTactualizapesocajc(vdartics *art,int error);
VDEXPORT int ARTactualizainterfase(vdartics *art,int error);
VDEXPORT int ARTactualizavdartic(vdartics *art,int error);
VDEXPORT int ARTinsert(vdartics *art,int error);
VDEXPORT int ARTdel(vdartics *art,int error);
VDEXPORT int ARTinter(vdartics *art);
VDEXPORT char *ARTlog(vdartics *art);
char * ARTdebug(vdartics *art);
