// Modulo generado automaticamente a partir de VDBULTOCAB.DEF

VDEXPORT diccionario dbuc;
#define BUCNUMCOL	57
typedef struct {
        char    rowid[ROWIDLON];
        char    codbulto[LCODBULTO];
        char    coddiv[LCODDIV];
        long    anoped;
        char    codped[LCODPED];
        long    seqped;
        long    nbulto;
        char    tipobulto[LTIPOBULTO];
        char    tipovol[LTIPOVOL];
        char    tipocaja[LTIPOCAJA];
        char    swtanular[LSWTANULAR];
        char    swtllevaalb[LSWTLLEVAALB];
        char    swtverifforzada[LSWTVERIFFORZADA];
        char    cntsscc[LCNTSSCC];
        char    matcaja[LMATCAJA];
        char    serierecogida[LSERIERECOGIDA];
        char    trackingage[LTRACKINGAGE];
        long    idinfopick;
        long    numdisp;
        double  pesoteorico;
        double  pesoreal;
        double  volumen;
        long    ultscan;
        long    fecultscan;
        char    horaultscan[LHORAULTSCAN];
        long    numrecirculaprep;
        long    numrecirculaverif;
        long    feccreado;
        char    horacreado[LHORACREADO];
        char    codopeimprime[LCODOPEIMPRIME];
        long    fecimprime;
        char    horaimprime[LHORAIMPRIME];
        char    codopeverifica[LCODOPEVERIFICA];
        long    fecverifica;
        char    horaverifica[LHORAVERIFICA];
        long    fecfinaliza;
        char    horafinaliza[LHORAFINALIZA];
        long    status;
        char    vdextra[LVDEXTRA];
        long    codcomen;
        char    codopemodif[LCODOPEMODIF];
        long    fecmodif;
        char    horamodif[LHORAMODIF];
        char    pedidohost[LPEDIDOHOST];
        char    codrecurso[LCODRECURSO];
        long    fecetiq;
        char    horaetiq[LHORAETIQ];
        long    fecfinpick;
        char    horafinpick[LHORAFINPICK];
        char    zonassgt[LZONASSGT];
        double  tara;
        long    codmovtermografo;
        char    codopetermografo[LCODOPETERMOGRAFO];
        long    fectermografo;
        char    horatermografo[LHORATERMOGRAFO];
        char    serietermografo[LSERIETERMOGRAFO];
        char    termografo[LTERMOGRAFO];
    } vdbultocabs;

// Prototipos de funciones definidas en VDBULTOCAB.C
VDEXPORT diccionario *BUCdamediccionario(void);
VDEXPORT int BUCbuscastatus(long status,vdbultocabs *buc);
VDEXPORT int BUCnextstatus(vdbultocabs *buc);
VDEXPORT int BUCbuscabultosdeunpedido(char *coddiv,long anoped,char *codped,long seqped,vdbultocabs *buc);
VDEXPORT int BUCnextbultosdeunpedido(vdbultocabs *buc);
VDEXPORT int BUCbuscabultostipoyvolu(char *coddiv,long anoped,char *codped,long seqped,char *tipobulto,char *tipovol,vdbultocabs *buc);
VDEXPORT int BUCnextbultostipoyvolu(vdbultocabs *buc);
VDEXPORT int BUCseldisplaystatus(long idinfopick,long numdisp,long status,vdbultocabs *buc);
VDEXPORT int BUCselvdbultocab(char *codbulto,vdbultocabs *buc);
VDEXPORT int BUClock(vdbultocabs *buc,int wait,int verificar,...);
VDEXPORT int BUCactualizallevaalbaran(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizaverificar(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizacodbulto(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizastatus(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizavolumenypeso(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizastatusypeso(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizapesoreal(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizanumrecirculaprep(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizanumrecirculaverif(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizascanner(vdbultocabs *buc,int error);
VDEXPORT int BUCactualizaimpresion(vdbultocabs *buc,int error);
VDEXPORT int BUCinsert(vdbultocabs *buc,int error);
VDEXPORT int BUCdel(vdbultocabs *buc,int error);
VDEXPORT char *BUClog(vdbultocabs *buc);
char * BUCdebug(vdbultocabs *buc);
