// Modulo generado automaticamente a partir de VDMOVIM.DEF

VDEXPORT diccionario dmov;
#define MOVNUMCOL	70
#define LCOMEN 1026
#define LMOVERPALET 2
typedef struct {
        char    rowid[ROWIDLON];
        long    codmov;
        char    codconce[LCODCONCE];
        char    datoshost[LDATOSHOST];
        char    codubiori[LCODUBIORI];
        char    codubitemp[LCODUBITEMP];
        char    codubidest[LCODUBIDEST];
        char    codmatori[LCODMATORI];
        char    codmattemp[LCODMATTEMP];
        char    codmatdest[LCODMATDEST];
        char    tipoconte[LTIPOCONTE];
        long    priomov;
        char    tarea[LTAREA];
        char    codrecurso[LCODRECURSO];
        char    solomueve[LSOLOMUEVE];
        long    codmovesp;
        long    codmovppaso;
        char    coddocumento[LCODDOCUMENTO];
        long    codinterfase;
        long    codpreparacion;
        long    status;
        char    bulto[LBULTO];
        char    codart[LCODART];
        char    codlot[LCODLOT];
        double  cantidad;
        char    bloqueosori[LBLOQUEOSORI];
        char    bloqueosdest[LBLOQUEOSDEST];
        char    tipoemba[LTIPOEMBA];
        double  uniemb;
        long    embcont;
        char    marcastk[LMARCASTK];
        char    numeroserie[LNUMEROSERIE];
        double  preciouni;
        double  pesouni;
        char    codrecep[LCODRECEP];
        long    codflujo;
        char    tipodemanda[LTIPODEMANDA];
        char    coddemanda[LCODDEMANDA];
        long    lindemanda;
        char    codopeins[LCODOPEINS];
        char    moduloins[LMODULOINS];
        char    accionins[LACCIONINS];
        long    fecins;
        char    horains[LHORAINS];
        char    moduloplanmov[LMODULOPLANMOV];
        char    accionplanmov[LACCIONPLANMOV];
        long    fecplanmov;
        char    horaplanmov[LHORAPLANMOV];
        char    codopeejemov[LCODOPEEJEMOV];
        char    moduloinimov[LMODULOINIMOV];
        char    accioninimov[LACCIONINIMOV];
        long    fecinimov;
        char    horainimov[LHORAINIMOV];
        char    modulofinmov[LMODULOFINMOV];
        char    accionfinmov[LACCIONFINMOV];
        long    fecfinmov;
        char    horafinmov[LHORAFINMOV];
        char    vdextra[LVDEXTRA];
        long    codcomen;
        char    codopemodif[LCODOPEMODIF];
        char    modulomodif[LMODULOMODIF];
        char    accionmodif[LACCIONMODIF];
        long    fecmodif;
        char    horamodif[LHORAMODIF];
        char    codbultoori[LCODBULTOORI];
        char    codbultodest[LCODBULTODEST];
        long    status1;
        long    status2;
        char    comen[LCOMEN];
        char    moverpalet[LMOVERPALET];
    } vdmovims;

// Prototipos de funciones definidas en VDMOVIM.C
VDEXPORT diccionario *MOVdamediccionario(void);
VDEXPORT int MOVbuscamismopalet(char *codmatori,char *moverpalet,long codmov,long status1,long status2,vdmovims *mov);
VDEXPORT int MOVnextmismopalet(vdmovims *mov);
VDEXPORT int MOVbuscacodmovesp(long codmov,vdmovims *mov);
VDEXPORT int MOVnextcodmovesp(vdmovims *mov);
VDEXPORT int MOVbuscastatus(long status,vdmovims *mov);
VDEXPORT int MOVnextstatus(vdmovims *mov);
VDEXPORT int MOVbuscastatusartmat(long status,vdmovims *mov);
VDEXPORT int MOVnextstatusartmat(vdmovims *mov);
VDEXPORT int MOVbuscademanda(char *tipodemanda,char *coddemanda,vdmovims *mov);
VDEXPORT int MOVnextdemanda(vdmovims *mov);
VDEXPORT int MOVbuscamovtostarea(char *codmatori,long codmov,long status1,char *tarea,vdmovims *mov);
VDEXPORT int MOVnextmovtostarea(vdmovims *mov);
VDEXPORT int MOVselvdmovim(long codmov,vdmovims *mov);
VDEXPORT int MOVlock(vdmovims *mov,int wait,int verificar,...);
VDEXPORT int MOVactualizareenganchamov(vdmovims *mov,int error);
VDEXPORT int MOVactualizaruta(vdmovims *mov,int error);
VDEXPORT int MOVactualizastatus(vdmovims *mov,int error);
VDEXPORT int MOVactualizaorigen(vdmovims *mov,int error);
VDEXPORT int MOVactualizadestino(vdmovims *mov,int error);
VDEXPORT int MOVactualizacantidad(vdmovims *mov,int error);
VDEXPORT int MOVactualizademanda(vdmovims *mov,int error);
VDEXPORT int MOVactualizamatriculas(vdmovims *mov,int error);
VDEXPORT int MOVactualizatarea(vdmovims *mov,int error);
VDEXPORT int MOVselvdsecprep(long *donde);
VDEXPORT int MOVselvdsecmovim(long *donde);
VDEXPORT int MOVinsert(vdmovims *mov,int error);
VDEXPORT int MOVdel(vdmovims *mov,int error);
VDEXPORT char *MOVlog(vdmovims *mov);
char * MOVdebug(vdmovims *mov);
