// Modulo generado automaticamente a partir de VDPEDIDORIGCAB.DEF

VDEXPORT diccionario dpoc;
#define POCNUMCOL	147
#define LCOMEN 1026
#define LMIROWID 1
typedef struct {
        char    rowid[ROWIDLON];
        char    coddiv[LCODDIV];
        long    anoped;
        char    codped[LCODPED];
        long    anoalb;
        char    codalb[LCODALB];
        char    tipopedido[LTIPOPEDIDO];
        long    nlineas;
        char    pedidocliente[LPEDIDOCLIENTE];
        long    fecpedidocliente;
        char    pedidohost[LPEDIDOHOST];
        char    codcliente[LCODCLIENTE];
        char    descliente[LDESCLIENTE];
        char    nif[LNIF];
        char    contacto[LCONTACTO];
        char    direccion[LDIRECCION];
        char    direccion1[LDIRECCION1];
        char    direccion2[LDIRECCION2];
        char    direccion3[LDIRECCION3];
        char    poblacion[LPOBLACION];
        char    codprov[LCODPROV];
        char    dp[LDP];
        char    codpais[LCODPAIS];
        char    telefono[LTELEFONO];
        char    fax[LFAX];
        char    email[LEMAIL];
        char    direccionedi[LDIRECCIONEDI];
        char    idiomaetiq[LIDIOMAETIQ];
        char    idiomadoc[LIDIOMADOC];
        long    numalba;
        char    menhost[LMENHOST];
        char    swtanular[LSWTANULAR];
        char    swtvalorado[LSWTVALORADO];
        char    swttotales[LSWTTOTALES];
        char    swtproforma[LSWTPROFORMA];
        char    swtalbexterior[LSWTALBEXTERIOR];
        char    swtalbsellado[LSWTALBSELLADO];
        char    portes[LPORTES];
        char    swtagrupar[LSWTAGRUPAR];
        char    swtcomunicar[LSWTCOMUNICAR];
        char    swtmodelo[LSWTMODELO];
        char    refmodelo[LREFMODELO];
        char    swtmiscelaneo[LSWTMISCELANEO];
        char    swtpackinglist[LSWTPACKINGLIST];
        char    swtnoetiqcc[LSWTNOETIQCC];
        char    swtpaletizar[LSWTPALETIZAR];
        char    swtetiqeci[LSWTETIQECI];
        char    swtbloqexp[LSWTBLOQEXP];
        char    swtmail[LSWTMAIL];
        char    swtfax[LSWTFAX];
        char    swtedi[LSWTEDI];
        char    codareaexped[LCODAREAEXPED];
        char    backorder[LBACKORDER];
        char    swtprepmono[LSWTPREPMONO];
        long    tpcverif;
        char    colcambiovol[LCOLCAMBIOVOL];
        char    moneda[LMONEDA];
        double  descuento;
        char    desdescuento[LDESDESCUENTO];
        double  recargo;
        char    desrecargo[LDESRECARGO];
        char    condpago[LCONDPAGO];
        long    prioridad;
        long    urgencia;
        char    codage[LCODAGE];
        char    trackingage[LTRACKINGAGE];
        char    datosage[LDATOSAGE];
        char    swtseguro[LSWTSEGURO];
        char    swtreembolso[LSWTREEMBOLSO];
        char    swtaduana[LSWTADUANA];
        long    recargoage;
        char    swtreexp[LSWTREEXP];
        char    codclireexp[LCODCLIREEXP];
        char    desclireexp[LDESCLIREEXP];
        char    nifreexp[LNIFREEXP];
        char    contareexp[LCONTAREEXP];
        char    dirreexp[LDIRREEXP];
        char    dirreexp1[LDIRREEXP1];
        char    dirreexp2[LDIRREEXP2];
        char    dirreexp3[LDIRREEXP3];
        char    pobreexp[LPOBREEXP];
        char    codprovreexp[LCODPROVREEXP];
        char    dpreexp[LDPREEXP];
        char    codpaisreexp[LCODPAISREEXP];
        char    telreexp[LTELREEXP];
        char    faxreexp[LFAXREEXP];
        char    emailreexp[LEMAILREEXP];
        char    direccionedireexp[LDIRECCIONEDIREEXP];
        char    swtfactu[LSWTFACTU];
        char    swtnumeroserie[LSWTNUMEROSERIE];
        char    codclifactu[LCODCLIFACTU];
        char    desclifactu[LDESCLIFACTU];
        char    niffactu[LNIFFACTU];
        char    contafactu[LCONTAFACTU];
        char    dirfactu[LDIRFACTU];
        char    dirfactu1[LDIRFACTU1];
        char    dirfactu2[LDIRFACTU2];
        char    dirfactu3[LDIRFACTU3];
        char    pobfactu[LPOBFACTU];
        char    codprovfactu[LCODPROVFACTU];
        char    dpfactu[LDPFACTU];
        char    codpaisfactu[LCODPAISFACTU];
        char    telfactu[LTELFACTU];
        char    faxfactu[LFAXFACTU];
        char    emailfactu[LEMAILFACTU];
        char    direccionedifactu[LDIRECCIONEDIFACTU];
        long    codcomen;
        long    feccaptura;
        char    horacaptura[LHORACAPTURA];
        long    fecservicio;
        long    fecgrabacion;
        char    horagrabacion[LHORAGRABACION];
        long    fecrecep;
        char    horarecep[LHORARECEP];
        long    fectermin;
        char    horatermin[LHORATERMIN];
        long    status;
        char    vdextra[LVDEXTRA];
        char    codopemodif[LCODOPEMODIF];
        long    fecmodif;
        char    horamodif[LHORAMODIF];
        double  baseseguro;
        char    cde[LCDE];
        double  difagencia;
        char    tipobaseseguro[LTIPOBASESEGURO];
        char    swtvolpedido[LSWTVOLPEDIDO];
        char    referenciacli[LREFERENCIACLI];
        char    sufijodoc[LSUFIJODOC];
        long    seqped;
        char    eci_comprador[LECI_COMPRADOR];
        char    eci_departamento[LECI_DEPARTAMENTO];
        char    eci_destino[LECI_DESTINO];
        char    eci_origen[LECI_ORIGEN];
        char    eci_proveedor[LECI_PROVEEDOR];
        char    eci_receptor[LECI_RECEPTOR];
        char    eci_sscc[LECI_SSCC];
        char    eci_sucursal[LECI_SUCURSAL];
        char    codopealta[LCODOPEALTA];
        char    clavepenitenciario[LCLAVEPENITENCIARIO];
        char    tipopedidoextra[LTIPOPEDIDOEXTRA];
        char    swtcajascompletas[LSWTCAJASCOMPLETAS];
        char    swtsepararcapas[LSWTSEPARARCAPAS];
        char    swtsepararreferencias[LSWTSEPARARREFERENCIAS];
        char    swtimpnodespaletizar[LSWTIMPNODESPALETIZAR];
        long    numpacklist;
        char    refagrupacion[LREFAGRUPACION];
        char    comen[LCOMEN];
    } vdpedidorigcabs;

// Prototipos de funciones definidas en VDPEDIDORIGCAB.C
VDEXPORT diccionario *POCdamediccionario(void);
VDEXPORT int POCbuscastatus(long status,vdpedidorigcabs *poc);
VDEXPORT int POCnextstatus(vdpedidorigcabs *poc);
VDEXPORT int POCselrowid(char *mirowid,vdpedidorigcabs *poc);
VDEXPORT int POCselvdpedidorigcab(char *coddiv,long anoped,char *codped,long seqped,vdpedidorigcabs *poc);
VDEXPORT int POClock(vdpedidorigcabs *poc,int wait,int verificar,...);
VDEXPORT int POCactualizastatus(vdpedidorigcabs *poc,int error);
VDEXPORT int POCactualizavdpedidorigcab(vdpedidorigcabs *poc,int error);
VDEXPORT int POCinsert(vdpedidorigcabs *poc,int error);
VDEXPORT int POCdel(vdpedidorigcabs *poc,int error);
VDEXPORT int POCinter(vdpedidorigcabs *poc);
VDEXPORT char *POClog(vdpedidorigcabs *poc);
char * POCdebug(vdpedidorigcabs *poc);
